### ISSUE TITLE
Decide where and how the supported quickstarts will be maintained

### ISSUE THREAD

**Issue by gastaldi** [obsidian-toaster/platform#1]
The backend needs to know what quickstarts are available to be displayed in the UI. 
Where should we keep that data and how?

**Comment by gastaldi** [comment]
I have a suggestion of having a separate Github repository having one file for each quickstart (YAML or JSON or XML) containing the metadata needed for the backend (supported language runtime, features, patterns, etc)

**Comment by gastaldi** [comment]
Just got an idea: to have a `ProjectType` that when executed will download the project content from a Github repository and do the appropriate changes (change groupId/artifactId for example) before returning the ZIP.

Pros: no need to update anything besides the github repository when updates to the quickstart are needed. 
Cons: We depend on Github being online (but we can also cache that)

**Comment by cmoulliard** [comment]
> ProjectType

So a project type will be mapped to a quickstart & will be used to download the artefact in order to populate the zip file after replacing the gav, package name ? @gastaldi

**Comment by gastaldi** [comment]
@cmoulliard when you talk about artifact, you mean something like https://github.com/obsidian-toaster/quick_rest_springboot-tomcat/archive/master.zip right? My idea is to grab that ZIP and unzip locally (or git clone), do the necessary changes, ZIP the directory and return to the user.

**Comment by cmoulliard** [comment]
> right

Yes

**Comment by cmoulliard** [comment]
So the yaml file could include such info

```
obsidian.yaml
  git:  https://github.com/obsidian-toaster/quick_rest_springboot-tomcat/archive/master.zip
  type: spring-boot
  patterns: 
    - jax-rs
    - secured-jax-rs
    - jpa
    - circuitbreaker
    - health
    - loadbalancing
  openshift: 
    - version: 3.3
    - components:
       - sso
       - metrics
       - apm
```
